### ISSUE TITLE
Package in Pypi doesn't install rdflib or pyld requirements

### ISSUE THREAD

**Issue by cbutcosk** [linked-art/crom#22]
I recently rebased a project's requirements and noticed that the cromulent package isn't installing crom's  `rdflib` or `pyld` requirements: 

```
sparrowhawk:crom-test incharge$ pip3 install cromulent ; python3 -c "from cromulent import vocab, model"
Collecting cromulent
  Using cached cromulent-0.16.3-py2.py3-none-any.whl
Installing collected packages: cromulent
Successfully installed cromulent-0.16.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/incharge/Projects/xxx/crom-test/ENV/lib/python3.7/site-packages/cromulent/vocab.py", line 5, in <module>
    from .model import Identifier, Mark, HumanMadeObject, Type, \
  File "/Users/incharge/Projects/xxx/crom-test/ENV/lib/python3.7/site-packages/cromulent/model.py", line 27, in <module>
    from pyld import jsonld
ModuleNotFoundError: No module named 'pyld'
```

**Comment by azaroth42** [comment]
I think we can probably let 2.x quietly go to the grave, where it should have been long ago!
Will add to `install_requires` but agree it would be nice to have them only imported if needed.

**Comment by azaroth42** [comment]
Try 0.16.5 and see if that works? Thanks Charlie!

**Comment by cbutcosk** [comment]
Aces: 
```
Successfully built cromulent
Installing collected packages: six, pyparsing, lxml, isodate, frozendict, cachetools, rdflib, PyLD, cromulent
Successfully installed PyLD-2.0.3 cachetools-4.2.2 cromulent-0.16.5 frozendict-2.0.2 isodate-0.6.0 lxml-4.6.3 pyparsing-2.4.7 rdflib-5.0.0 six-1.16.0
(ENV) sparrowhawk:crom-test incharge$ python3.7 -c "from cromulent import vocab,model" 
RDFLib Version: 5.0.0
```

It does break a virtualenv with 2.7.16 as the interpreter but if that is a necessary profile for someone, pinning pyld to an earlier (pre-`2.x`?) for 2.7.X interpreters may work in a pinch. But I think that's more of a congratulations on crom's new slim-n-trim python dependencies. 😀

Thanks Rob!

**Comment by azaroth42** [comment]
Realized that the linked.art site still (gulp) relies on hyde which is only 2.x :/

Need to work on https://github.com/linked-art/linked.art/pull/352

**Comment by cbutcosk** [comment]
Hmm, returning to this many moons later--it looks like the linked PR is merged, does that mean the package metadata can be updated to show only Python 3 dependencies? I have this on a fork (along with the corresponding `setup.cfg` changes) if useful, PR-wise

**Comment by azaroth42** [comment]
Fixed! Try with 0.17.1 and see if it works please

**Comment by cbutcosk** [comment]
Delightful, thanks rob! I think that means you can also remove [this](https://github.com/linked-art/crom/blob/3bfad9364146335334bced236e78379327b50ef1/setup.cfg#L1) line in `setup.cfg` as well, which is forcing a 2-3 compatible wheel.

FWIW the reasoning here is that I'm using cromulent via [micropip](https://pyodide.org/en/stable/usage/api/micropip-api.html), which [pyodide](https://pyodide.org/en/stable/) uses for package management in its python-over-wasm implementation. Amazingly the whole `crom` package works fine there (as long as I strip out the pyld / rdflib deps)!

**Comment by azaroth42** [comment]
Thanks Charlie!
